### ISSUE TITLE
Fails to Parse classNames with Child, Sibling, and Direct Child Selectors

### ISSUE THREAD

**Issue by ajth-in** [ajth-in/muffincss#14]
**Describe the bug**

fails to parse and compile class selectors that use relational combinators. These include child (>), adjacent sibling (+), and general sibling (~) selectors. As a result, any styles defined using these selectors are omitted in the final output.

**To Reproduce**
try compiling 
```css
.button {
  padding: 12px;
}

.button > .icon {
  margin-left: 8px;
}

.button + .tooltip {
  display: block;
}
```

**Expected behavior**
Expecting standard css behaviour for css selectors

**Context (please complete the following information):**
- Framework/Tools: Tanstack start
