### ISSUE TITLE
Support Themed Tokens Using @token At-Rule with Dynamic Value Switching

### ISSUE THREAD

**Issue by ajth-in** [ajth-in/muffincss#16]
**Is your feature request related to a problem? Please describe.**
There’s no easy way to define CSS tokens with multiple theme values (e.g., light and dark) and switch them based on the user’s theme.

**Describe the solution you'd like**
Add support for an @token at-rule like:
```css
@token {
  --token-name: value-light;
  --token-name-dark: value-dark;
}
```
The plugin should output a single --token-name variable and switch its value automatically depending on the selected theme.
