### ISSUE TITLE
Attribute Selectors with Complex ClassNames Not Parsed

### ISSUE THREAD

**Issue by ajth-in** [ajth-in/muffincss#21]
**Describe the bug**
CSS selectors that combine class names with attribute selectors (like .react-aria-TabList[data-orientation="horizontal"]) are not being parsed or processed correctly by the preprocessor.

**To Reproduce**
```css
.react-aria-TabList[data-orientation="horizontal"] {
  display: flex;
}
```
Compile using the plugin, Observe that the rule is ignored or missing in the output.
