### ISSUE TITLE
Inconsistent Output with Multiple Media Queries for Same ClassName

### ISSUE THREAD

**Issue by ajth-in** [ajth-in/muffincss#22]
**Describe the bug**

When defining multiple media queries for the same className, some media rules are missing in the compiled output.

**To Reproduce**
```css
.button {
  padding: 8px;
}

@media (min-width: 640px) {
  .button {
    padding: 12px;
  }
}

@media (min-width: 1024px) {
  .button {
    padding: 16px;
  }
}
```

Compile the CSS, Notice that one or more media queries are not included in the final output.
