### ISSUE TITLE
Media query property conflict

### ISSUE THREAD

**Issue by ajth-in** [ajth-in/muffincss#38]
**Describe the bug**
 When the same property is defined both in a base rule and inside a media query, the value from the base rule is always taking precedence, even within the media query context. This causes the media query version of the property to be ignored.

**To Reproduce**
```css
.navbar__links {
  /* display: none; */
  color: red;
  align-items: center;
  gap: 1rem;
  font-size: 0.875rem; /* text-sm */
  font-weight: 500;     /* font-medium */
  /* color: var(--muted-foreground); */
}

@media (min-width: 1024px) {
  .navbar__links {
    display: flex;
    color: blue;
    background-color: yellow;
  }
}

```
In this example, the color remains red even at larger screen widths, while background-color correctly switches to yellow as defined in the media query.
